"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ui } from "../ui";
import { BrandMark } from "../brand-mark";
export function BootstrapForm(){
  const router=useRouter();const [required,setRequired]=useState<boolean|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
  useEffect(()=>{fetch("/api/bootstrap").then(r=>r.json()).then(x=>setRequired(x.required)).catch(()=>setError("Could not reach the FieldOps server."))},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget);const response=await fetch("/api/bootstrap",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(data))});const body=await response.json();setBusy(false);if(!response.ok){setError(body.error);return}router.replace("/login")}
  if(required===null)return <main className="grid min-h-screen place-items-center bg-slate-50 font-bold text-[#2D2729]">Checking secure setup…</main>;
  if(!required)return <main className="grid min-h-screen place-items-center bg-slate-50 p-6 text-center"><div><h2 className={ui.h2}>FieldOps is already initialized.</h2><a className={`${ui.button} mt-5`} href="/login">Go to sign in</a></div></main>;
  return <main className="grid min-h-screen bg-slate-50 text-[#2D2729] lg:grid-cols-[minmax(320px,.9fr)_minmax(430px,1.1fr)]"><section className="flex min-h-[340px] flex-col justify-between bg-[#2D2729] p-8 text-white sm:p-12 lg:p-[clamp(48px,5vw,76px)]"><div className="flex items-center gap-3"><span className={ui.logo}><BrandMark className="h-full w-full" /></span><div><strong className="block text-sm">Yousuf Rice FieldOps</strong><small className="mt-1 block text-slate-400">Secure initialization</small></div></div><div><p className="text-[11px] font-black uppercase tracking-[0.13em] text-slate-400">First administrator</p><h1 className="my-3 text-4xl font-black leading-none tracking-[-0.045em] sm:text-6xl">Open the control room.</h1><p className="max-w-xl leading-7 text-slate-300">This one-time step creates the Yousuf Rice organization, your Appwrite account and the server-managed admin label used for dashboard access.</p></div></section><section className="grid place-items-center bg-white p-6 sm:p-10"><form className="w-full max-w-md" onSubmit={submit}><p className={ui.eyebrow}>One-time setup</p><h2 className="my-3 text-3xl font-black tracking-tight">Create administrator</h2><label className={`${ui.label} my-4`}>Your name<input className={ui.input} name="name" autoComplete="name" required/></label><label className={`${ui.label} my-4`}>Work email<input className={ui.input} name="email" type="email" autoComplete="email" required/></label><label className={`${ui.label} my-4`}>Password<input className={ui.input} name="password" type="password" minLength={12} autoComplete="new-password" required/><small className="font-medium text-slate-500">At least 12 characters</small></label><label className={`${ui.label} my-4`}>Bootstrap key<input className={ui.input} name="bootstrapToken" type="password" required/></label>{error&&<p className={ui.messageError} role="alert">{error}</p>}<button className={`${ui.button} mt-4 w-full`} disabled={busy}>{busy?"Creating workspace…":"Create secure workspace"}</button></form></section></main>
}
