export const ui = {
  page: "min-h-screen bg-slate-50 text-[#14213D] antialiased",
  shell: "min-h-screen bg-[#F8FAFC] text-[#14213D] lg:grid lg:grid-cols-[252px_minmax(0,1fr)]",
  rail: "sticky top-0 z-40 flex flex-col bg-[#14213D] px-3 py-3 text-white shadow-[0_8px_28px_rgba(20,33,61,0.18)] lg:h-screen lg:px-[18px] lg:py-7 lg:shadow-none",
  brand: "flex items-center gap-3 px-2 pb-3 lg:pb-8",
  logo: "grid h-11 w-11 shrink-0 place-items-center rounded-[14px] bg-[#2563EB] font-black text-white",
  nav: "flex gap-1 overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden lg:grid lg:overflow-visible lg:pb-0",
  navLink: "flex min-h-11 cursor-pointer items-center gap-2.5 rounded-xl px-3.5 py-2.5 text-sm font-bold text-slate-300 transition-colors hover:bg-white/10 hover:text-white focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-blue-300",
  navSelected: "bg-[#254A9A] text-white shadow-[inset_3px_0_#60A5FA]",
  workspace: "mx-auto w-full max-w-[1540px] px-4 py-7 sm:px-6 lg:px-10 lg:py-10 xl:px-14",
  eyebrow: "m-0 text-[11px] font-black uppercase tracking-[0.13em] text-slate-500",
  h1: "my-2 text-3xl font-black leading-[1.04] tracking-[-0.04em] text-[#14213D] sm:text-4xl xl:text-5xl",
  h2: "my-1 text-2xl font-black tracking-[-0.025em] text-[#14213D]",
  lede: "max-w-3xl leading-7 text-slate-600",
  card: "self-start rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_10px_30px_rgba(20,33,61,0.055)] sm:p-6",
  sectionHead: "flex flex-col items-start justify-between gap-3 sm:flex-row",
  label: "grid gap-2 text-xs font-extrabold text-[#14213D]",
  input: "min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-[#14213D] outline-none transition focus:border-blue-600 focus:ring-3 focus:ring-blue-200",
  button: "inline-flex min-h-11 items-center justify-center rounded-xl bg-[#2563EB] px-4 py-2.5 font-extrabold text-white transition hover:bg-blue-700 focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-blue-300 disabled:cursor-not-allowed disabled:opacity-45",
  quietButton: "inline-flex min-h-11 items-center justify-center rounded-xl border border-slate-300 bg-white px-4 py-2.5 font-extrabold text-[#14213D] transition hover:bg-slate-50 focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-blue-300 disabled:cursor-not-allowed disabled:opacity-45",
  dangerButton: "inline-flex min-h-11 items-center justify-center rounded-xl border border-red-200 bg-red-50 px-4 py-2.5 font-extrabold text-red-800 transition hover:bg-red-100 focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-red-300 disabled:cursor-not-allowed disabled:opacity-45",
  messageError: "border-l-4 border-red-600 bg-red-50 p-3 text-sm font-bold text-red-800",
  messageSuccess: "border-l-4 border-emerald-600 bg-emerald-50 p-3 text-sm font-bold text-emerald-800",
  tableWrap: "overflow-x-auto",
  tableCard: "mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_10px_30px_rgba(20,33,61,0.055)] sm:p-6",
  table: "mt-5 w-full border-collapse text-left text-sm [&_th]:border-t [&_th]:border-slate-200 [&_th]:px-3 [&_th]:py-3 [&_th]:text-[10px] [&_th]:font-black [&_th]:uppercase [&_th]:tracking-[0.08em] [&_th]:text-slate-500 [&_td]:min-w-28 [&_td]:border-t [&_td]:border-slate-200 [&_td]:px-3 [&_td]:py-3 [&_td]:align-top [&_small]:mt-1 [&_small]:block [&_small]:text-slate-500",
  th: "border-t border-slate-200 px-3 py-3 text-[10px] font-black uppercase tracking-[0.08em] text-slate-500",
  td: "min-w-28 border-t border-slate-200 px-3 py-3 align-top",
} as const;
