export const ui = {
  page: "min-h-screen bg-[var(--canvas)] text-[var(--ink)] antialiased",
  shell: "min-h-screen bg-[var(--canvas)] text-[var(--ink)] lg:grid lg:grid-cols-[248px_minmax(0,1fr)]",
  rail: "dashboard-rail sticky top-0 z-40 flex max-h-dvh flex-col bg-[#292526] px-3 py-3 text-white lg:h-dvh lg:px-4 lg:py-7",
  brand: "flex items-center gap-3 px-2 py-2 lg:mb-7",
  logo: "grid h-12 w-12 shrink-0 place-items-center overflow-hidden rounded-2xl bg-[#F7F7F7]",
  nav: "flex gap-1 overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden lg:grid lg:overflow-visible lg:pb-0",
  navLink: "group flex min-h-11 items-center gap-3 rounded-xl px-3.5 py-2.5 text-[13px] font-semibold text-[#C6BDBF] transition-colors hover:bg-white/5 hover:text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#F6A9B8]",
  navSelected: "bg-[#CB183D] text-white shadow-[0_6px_18px_#12030533] hover:bg-[#B81134] hover:text-white",
  workspace: "dashboard-workspace relative mx-auto w-full max-w-[1600px] px-4 py-6 sm:px-7 lg:px-9 lg:py-8 xl:px-12",
  eyebrow: "m-0 font-utility text-[10px] font-bold uppercase tracking-[0.14em] text-[var(--muted)]",
  h1: "font-display my-2 max-w-4xl text-[30px] font-bold leading-[1.12] tracking-[-0.035em] sm:text-[36px]",
  h2: "font-display my-1 text-[22px] font-bold tracking-[-0.025em] text-[var(--ink)]",
  lede: "max-w-2xl text-sm leading-6 text-[var(--muted)]",
  pageHeader: "page-header mb-6 flex flex-col items-start justify-between gap-4 rounded-[24px] px-6 py-7 sm:px-8 xl:flex-row xl:items-center",
  card: "self-start rounded-[22px] border border-[var(--line)] bg-white p-5 shadow-[0_5px_22px_#46202405] sm:p-6",
  sectionHead: "flex flex-col items-start justify-between gap-3 sm:flex-row sm:items-center",
  label: "grid gap-2 text-xs font-semibold text-[var(--ink)]",
  input: "min-h-11 w-full rounded-xl border border-[var(--line)] bg-white px-3 py-2.5 text-sm text-[var(--ink)] outline-none transition-colors placeholder:text-[#998D90] focus:border-[var(--brand)] focus:ring-3 focus:ring-[#FADEE5]",
  button: "inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[var(--brand)] px-4 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-[#AB1232] focus-visible:outline-2 focus-visible:outline-offset-3 focus-visible:outline-[var(--brand)] disabled:cursor-not-allowed disabled:opacity-45",
  quietButton: "inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-[var(--line)] bg-white px-4 py-2.5 text-sm font-semibold text-[var(--ink)] transition-colors hover:border-[#D6A7B2] hover:bg-[#FFF6F8] focus-visible:outline-2 focus-visible:outline-offset-3 focus-visible:outline-[var(--brand)] disabled:cursor-not-allowed disabled:opacity-45",
  dangerButton: "inline-flex min-h-11 items-center justify-center rounded-xl border border-[#F0B8B1] bg-[#FFF2F0] px-4 py-2.5 text-sm font-semibold text-[#A43B32] transition-colors hover:bg-[#FFE6E2] focus-visible:outline-2 focus-visible:outline-offset-3 focus-visible:outline-[#A43B32] disabled:cursor-not-allowed disabled:opacity-45",
  messageError: "rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800",
  messageSuccess: "rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800",
  tableWrap: "overflow-x-auto",
  tableCard: "mt-5 overflow-hidden rounded-[22px] border border-[var(--line)] bg-white p-5 shadow-[0_5px_22px_#46202405] sm:p-6",
  table: "mt-5 w-full border-collapse text-left text-sm [&_tbody_tr]:transition-colors [&_tbody_tr:hover]:bg-[#FFF8F9] [&_th]:border-b [&_th]:border-[var(--line)] [&_th]:bg-[#FAF7F5] [&_th]:px-3 [&_th]:py-3 [&_th]:text-[11px] [&_th]:font-semibold [&_th]:text-[var(--muted)] [&_td]:min-w-28 [&_td]:border-b [&_td]:border-[#F2ECE9] [&_td]:px-3 [&_td]:py-4 [&_td]:align-top [&_tbody_tr:last-child_td]:border-b-0 [&_small]:mt-1 [&_small]:block [&_small]:text-[var(--muted)]",
  th: "border-b border-[var(--line)] px-3 py-3 text-xs font-semibold text-[var(--muted)]",
  td: "min-w-28 border-b border-[var(--line)] px-3 py-4 align-top",
} as const;
